version: "3.8"
services:
  adjectives:
    image: microservice
    build:
      context: microservice
      dockerfile: v4-experimental-cache.Dockerfile
    expose:
      - "3000"
    ports:
      - "3001:3000"
    volumes:
      - ./microservice/resources/adjectives.txt:/list.txt:ro
  nouns:
    image: microservice
    expose:
      - "3000"
    ports:
      - "3002:3000"
    volumes:
      - ./microservice/resources/nouns.txt:/list.txt:ro
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: v3-experimental-cache.Dockerfile
    ports:
      - "8080:8080"
